// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh2Xh7Q_FS-ypi8attSsCne1QfnqOGUJU',
    appId: '1:244664483194:web:fc859e8136a8184fdaeac3',
    messagingSenderId: '244664483194',
    projectId: 'quantic-964f1',
    authDomain: 'quantic-964f1.firebaseapp.com',
    storageBucket: 'quantic-964f1.appspot.com',
    measurementId: 'G-NVXN4633N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPUaxFke6rxwZOTvX_nNQI0T-t6UJk-8',
    appId: '1:244664483194:android:2e1a8ad3239d727ddaeac3',
    messagingSenderId: '244664483194',
    projectId: 'quantic-964f1',
    storageBucket: 'quantic-964f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOrZL-OGPLFZO6ekoxrL6BXbYqLTOP0Q',
    appId: '1:244664483194:ios:57071c72632b6228daeac3',
    messagingSenderId: '244664483194',
    projectId: 'quantic-964f1',
    storageBucket: 'quantic-964f1.appspot.com',
    iosClientId: '244664483194-jtsgdt36j3umsti8j223hjn260ji94be.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOOrZL-OGPLFZO6ekoxrL6BXbYqLTOP0Q',
    appId: '1:244664483194:ios:57071c72632b6228daeac3',
    messagingSenderId: '244664483194',
    projectId: 'quantic-964f1',
    storageBucket: 'quantic-964f1.appspot.com',
    iosClientId: '244664483194-jtsgdt36j3umsti8j223hjn260ji94be.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh2Xh7Q_FS-ypi8attSsCne1QfnqOGUJU',
    appId: '1:244664483194:web:8ae978f404a0c1a6daeac3',
    messagingSenderId: '244664483194',
    projectId: 'quantic-964f1',
    authDomain: 'quantic-964f1.firebaseapp.com',
    storageBucket: 'quantic-964f1.appspot.com',
    measurementId: 'G-5LK6VXW0QF',
  );
}
